### ISSUE TITLE
FAILED: RuntimeException Cannot create staging directory  when run hive srcipt 

### ISSUE THREAD

**Issue by fengshenwu** [aliyun/aliyun-emapreduce-sdk#120]
[hadoop@emr-header-1 ~]$ hadoop fs -mkdir oss://id:key@hive.oss-cn-hangzhou-internal.aliyuncs.com/test6/11
mkdir: Permission denied

i found  /mnt/disk1/data/oss user:group is root:root

```
[hadoop@emr-header-1 ~]$ cd /mnt/disk1/data
[hadoop@emr-header-1 data]$ ll
total 4
drwxr-xr-x 2 root root 4096 Apr 18 18:23 oss
```

delete /mnt/disk1/data，when Run the following script to be successful 
```
[hadoop@emr-header-1 ~]$ hadoop fs -mkdir oss://id:key@hive.oss-cn-hangzhou-internal.aliyuncs.com/test6/11
```

**Comment by uncleGen** [comment]
fixed by #133
