### ISSUE TITLE
Emr对接阿里云Kafka，有对应的Demo吗

### ISSUE THREAD

**Issue by dongeforever** [aliyun/aliyun-emapreduce-sdk#188]

**Comment by dongeforever** [comment]
@uncleGen

**Comment by uncleGen** [comment]
@dongeforever E-MapReduce支持创建Kafka集群。你可以看下这个文档https://help.aliyun.com/document_detail/56932.html

**Comment by dongeforever** [comment]
@uncleGen 我们现在有业务已经接入阿里云Kafka了，希望有一个快速的办法把阿里云Kafka的数据导入EMR集群内；
我看EMR是可以和ONS对接的；为啥不能和Kafka对接呢；

**Comment by uncleGen** [comment]
你所的对接是啥意思？

**Comment by dongeforever** [comment]
就是我开通了阿里云Kafka，现在想把数据接入EMR集群里面跑，类似于https://help.aliyun.com/document_detail/28120.html?spm=5176.doc56932.6.630.ntErfw

**Comment by uncleGen** [comment]
现在还没有demo，理论上自定义一个receiver是很方便实现的。

**Comment by uncleGen** [comment]
直接使用spark提供的kafka接口也是可以的
