### ISSUE TITLE
DatahubRDD 'count' should initial in each ShardPartition 

### ISSUE THREAD

**Issue by StephenShang** [aliyun/aliyun-emapreduce-sdk#282]
**Describe the bug**

https://github.com/aliyun/aliyun-emapreduce-sdk/blob/v1.6.0/emr-datahub/src/main/scala/org/apache/spark/streaming/aliyun/datahub/DatahubRDD.scala

line 78

count should be initialled in the loop, like:

override protected def getPartitions: Array[Partition] = {
    val rate = _sc.getConf.get("spark.streaming.datahub.maxRatePerShard", "10000").toInt
    **// var count = rate * duration / 1000**
    datahubClientAgent = DatahubRDD.getClient(zkParam, accessId, accessKey, endpoint)._2
    shardOffsets.zipWithIndex.map {
      case (so, index) =>
        val shardId = so._1
        val startOffset = JacksonParser.getOffset(so._2)
        val endOffset = JacksonParser.getOffset(so._3)
        **var count = rate * duration / 1000**
        if (count > endOffset.getSequence - startOffset.getSequence + 1) {
          count = endOffset.getSequence - startOffset.getSequence + 1
        }
        val cursor = datahubClientAgent.getCursor(project, topic, shardId, startOffset).getCursor
        new ShardPartition(id, shardId, index, cursor, count.toInt).asInstanceOf[Partition]
    }.toArray
  }
}

otherwise, count of all Partition maybe be set to a very small value, if the first Partition has less elements.

**Comment by uncleGen** [comment]
@StephenShang make sense, could you please give a pr to fix this?
