### ISSUE TITLE
System.gc() make Full GC very frequent

### ISSUE THREAD

**Issue by tianshuang** [aliyun/aliyun-emapreduce-sdk#367]
**Is your feature request related to a problem? Please describe.**
[GC report](https://gceasy.io/my-gc-report.jsp?p=c2hhcmVkLzIwMTkvMTAvMTEvLS1zcGFyay5nYy0tMTItNDgtOQ==&channel=WEB)
Manually calling this method causes Spark to take up too much GC time for OSS. It is recommended to remove the method call.

**Describe the solution you'd like**
It is not recommended to call this method manually, and the virtual machine handles the GC. It is recommended to delete this line of code.

**Comment by tianshuang** [comment]
https://github.com/aliyun/aliyun-emapreduce-sdk/blob/bb838ecf481926cba81ebec2f5dbc1198ffe73a3/emr-oss/src/main/java/com/aliyun/fs/oss/nat/BufferReader.java#L141

**Comment by tianshuang** [comment]
[Guide to System.gc()](https://www.baeldung.com/java-system-gc)

**Comment by uncleGen** [comment]
Could you please provide a PullRequest?

**Comment by tianshuang** [comment]
https://github.com/aliyun/aliyun-emapreduce-sdk/pull/369

**Comment by uncleGen** [comment]
Thanks
