### ISSUE TITLE
是否能出一个SBT的工程。

### ISSUE THREAD

**Issue by shengnoah** [aliyun/aliyun-emapreduce-sdk#46]
能不能出一个SBT的sample工程，可以用于自动下载org包的依赖，也便于在运行的时候集成com包人依赖，像osscmd一样，可以跟踪sdk、core模块的变更，验证接口的变更。

在编译和运行阶段都能应用到测试有效性上。

**Comment by shengnoah** [comment]
现在运行core的mvn test貌似通不过。

**Comment by shengnoah** [comment]
core 的mvn test过不了。

**Comment by uncleGen** [comment]
哪个TC过不了，提issue把

**Comment by uncleGen** [comment]
@shengnoah  欢迎贡献代码：）

**Comment by shengnoah** [comment]
@uncleGen  我给你的gmal邮箱发了一封信，留了QQ号，方便QQ交流一下吗？
共享写测试CASE代码没问题：）
