### ISSUE TITLE
 包的依赖关系和com.aliyun.fs.oss.nat.NativeOssFileSystem

### ISSUE THREAD

**Issue by shengnoah** [aliyun/aliyun-emapreduce-sdk#50]
Core目录可以compile，mvn test不错，但可以跳过test  生成.jar包。
SDK->依赖Core

已经将emr-sdk_2.0跳过test ， 生成jar包，进行了本地化安全。

并在要调用emr-sdk的.jar客户端程序的.pom加入了, emr-sdk的依赖。

    <dependency>
      <groupId>com.aliyun</groupId>
      <artifactId>emr-sdk_2.10</artifactId>
      <version>1.0.0</version>
    </dependency>

因为emr-sdk已经mvn install， 编译阶段是可以通过的。 
但是在执行阶段， 即使把core和sdk生成一个包里，还会出现，找不到core的NativeOssFileSystem类的问题。com.aliyun.fs.oss.nat.NativeOssFileSystem

如果直接把core打成一个包， 放到工程的classpath中，出现另外的异常。

com/aliyun/oss/ServiceException

**Comment by uncleGen** [comment]
@shengnoah 你可以解开Jar包看看，里面到底打进去没有

**Comment by shengnoah** [comment]
shaded里的有， 不是shaded里没有...

**Comment by uncleGen** [comment]
ok
