### ISSUE TITLE
在哪里可以下载到sls-loghub-client-inner？

### ISSUE THREAD

**Issue by Inza9hi** [aliyun/aliyun-emapreduce-sdk#75]
[ERROR] Failed to execute goal on project emr-sdk_2.10: Could not resolve dependencies for project com.aliyun:emr-sdk_2.10:jar:1.0.5-SNAPSHOT: Could not find artifact com.aliyun:sls-loghub-client-inner:jar:0.1.4 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by uncleGen** [comment]
loghub相关的SDK还在测试中，等公开了就可以编译了。如果你只是想使用的话，可以直接使用已经编译好的Jar包，地址在https://help.aliyun.com/document_detail/emr/best-practice/Spark/%E5%BC%80%E5%8F%91%E5%87%86%E5%A4%87.html?spm=5176.product9091098_emr.6.119.NesKa5
